### ISSUE TITLE
特定の条件下でdragEnd時にdropped側が取得できずにboard内判定ができない

### ISSUE THREAD

**Issue by shuto410** [shuto410/board-game-simulator#18]
これにより現在、うまくplaceをドラッグ&ドロップができない時がある

**Comment by shuto410** [comment]
dragの移動量などは正確に取得できるが、board内からboard内に移動させた際に移動後のdropped側がboardになってくれない
おそらく同じdroppable element内でのdrag&dropはdnd側で想定されていない
board内にdropしたどうかの判定はこっちで実装する必要があると思われる

**Comment by sho25** [comment]
https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/core-draggable-hooks-usedraggable--snap-to-grid
これだと発生しなくて
https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/core-droppable-usedroppable--basic-setup
これだと発生する
